drop table if exists {database}.{schema}.{table};

create table {database}.{schema}.{table} (
  A nvarchar(max)
{column 2}, B nvarchar(max)
{column 3}, C nvarchar(max)
{column 4}, D nvarchar(max)
{column 5}, E nvarchar(max)
{column 6}, F nvarchar(max)
{column 7}, G nvarchar(max)
{column 8}, H nvarchar(max)
{column 9}, I nvarchar(max)
{column 10}, J nvarchar(max)
{column 11}, K nvarchar(max)
{column 12}, L nvarchar(max)
{column 13}, M nvarchar(max)
{column 14}, N nvarchar(max)
{column 15}, O nvarchar(max)
{column 16}, P nvarchar(max)
{column 17}, Q nvarchar(max)
{column 18}, R nvarchar(max)
{column 19}, S nvarchar(max)
{column 20}, T nvarchar(max)
{column 21}, U nvarchar(max)
{column 22}, V nvarchar(max)
{column 23}, W nvarchar(max)
{column 24}, X nvarchar(max)
{column 25}, Y nvarchar(max)
{column 26}, Z nvarchar(max)
);